# Form implementation generated from reading ui file 'osc_main_window.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OscMainWindow(object):
    def setupUi(self, OscMainWindow):
        OscMainWindow.setObjectName("OscMainWindow")
        OscMainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(OscMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        OscMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OscMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        OscMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OscMainWindow)
        self.statusbar.setObjectName("statusbar")
        OscMainWindow.setStatusBar(self.statusbar)
        self.build_mr_action = QtGui.QAction(OscMainWindow)
        self.build_mr_action.setObjectName("build_mr_action")
        self.exit_action = QtGui.QAction(OscMainWindow)
        self.exit_action.setObjectName("exit_action")
        self.menu.addAction(self.build_mr_action)
        self.menu.addSeparator()
        self.menu.addAction(self.exit_action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(OscMainWindow)
        QtCore.QMetaObject.connectSlotsByName(OscMainWindow)

    def retranslateUi(self, OscMainWindow):
        _translate = QtCore.QCoreApplication.translate
        OscMainWindow.setWindowTitle(_translate("OscMainWindow", "Осциллограмма"))
        self.menu.setTitle(_translate("OscMainWindow", "АХ"))
        self.build_mr_action.setText(_translate("OscMainWindow", "Построить АХ..."))
        self.exit_action.setText(_translate("OscMainWindow", "Закрыть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OscMainWindow = QtWidgets.QMainWindow()
    ui = Ui_OscMainWindow()
    ui.setupUi(OscMainWindow)
    OscMainWindow.show()
    sys.exit(app.exec())
