# Form implementation generated from reading ui file 'on_mr_build_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OnMrBuildDialog(object):
    def setupUi(self, OnMrBuildDialog):
        OnMrBuildDialog.setObjectName("OnMrBuildDialog")
        OnMrBuildDialog.resize(719, 542)
        self.buttonBox = QtWidgets.QDialogButtonBox(OnMrBuildDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 480, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.sequence_combo_box = QtWidgets.QComboBox(OnMrBuildDialog)
        self.sequence_combo_box.setGeometry(QtCore.QRect(230, 20, 111, 22))
        self.sequence_combo_box.setObjectName("sequence_combo_box")
        self.sequence_label = QtWidgets.QLabel(OnMrBuildDialog)
        self.sequence_label.setGeometry(QtCore.QRect(20, 20, 201, 16))
        self.sequence_label.setObjectName("sequence_label")
        self.grid_group_box = QtWidgets.QGroupBox(OnMrBuildDialog)
        self.grid_group_box.setGeometry(QtCore.QRect(10, 70, 491, 391))
        self.grid_group_box.setCheckable(True)
        self.grid_group_box.setObjectName("grid_group_box")
        self.grid_table_view = QtWidgets.QTableView(self.grid_group_box)
        self.grid_table_view.setGeometry(QtCore.QRect(10, 50, 221, 331))
        self.grid_table_view.setObjectName("grid_table_view")
        self.groupBox = QtWidgets.QGroupBox(self.grid_group_box)
        self.groupBox.setGeometry(QtCore.QRect(239, 19, 241, 361))
        self.groupBox.setObjectName("groupBox")
        self.tableView = QtWidgets.QTableView(self.groupBox)
        self.tableView.setGeometry(QtCore.QRect(10, 30, 221, 331))
        self.tableView.setObjectName("tableView")

        self.retranslateUi(OnMrBuildDialog)
        self.buttonBox.accepted.connect(OnMrBuildDialog.accept)
        self.buttonBox.rejected.connect(OnMrBuildDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OnMrBuildDialog)

    def retranslateUi(self, OnMrBuildDialog):
        _translate = QtCore.QCoreApplication.translate
        OnMrBuildDialog.setWindowTitle(_translate("OnMrBuildDialog", "Dialog"))
        self.sequence_label.setText(_translate("OnMrBuildDialog", "Порядок изменения физ. величины:"))
        self.grid_group_box.setTitle(_translate("OnMrBuildDialog", "Использовать сетку"))
        self.groupBox.setTitle(_translate("OnMrBuildDialog", "GroupBox"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OnMrBuildDialog = QtWidgets.QDialog()
    ui = Ui_OnMrBuildDialog()
    ui.setupUi(OnMrBuildDialog)
    OnMrBuildDialog.show()
    sys.exit(app.exec())
