# Form implementation generated from reading ui file 'on_mr_build_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OnMrBuildDialog(object):
    def setupUi(self, OnMrBuildDialog):
        OnMrBuildDialog.setObjectName("OnMrBuildDialog")
        OnMrBuildDialog.resize(531, 811)
        self.buttonBox = QtWidgets.QDialogButtonBox(OnMrBuildDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 750, 511, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.sequence_combo_box = QtWidgets.QComboBox(OnMrBuildDialog)
        self.sequence_combo_box.setGeometry(QtCore.QRect(230, 20, 111, 22))
        self.sequence_combo_box.setObjectName("sequence_combo_box")
        self.sequence_label = QtWidgets.QLabel(OnMrBuildDialog)
        self.sequence_label.setGeometry(QtCore.QRect(20, 20, 201, 16))
        self.sequence_label.setObjectName("sequence_label")
        self.grid_group_box = QtWidgets.QGroupBox(OnMrBuildDialog)
        self.grid_group_box.setGeometry(QtCore.QRect(10, 60, 511, 671))
        self.grid_group_box.setCheckable(True)
        self.grid_group_box.setObjectName("grid_group_box")
        self.down_grid_group_box = QtWidgets.QGroupBox(self.grid_group_box)
        self.down_grid_group_box.setGeometry(QtCore.QRect(250, 20, 251, 541))
        self.down_grid_group_box.setCheckable(True)
        self.down_grid_group_box.setObjectName("down_grid_group_box")
        self.down_grid_table_view = QtWidgets.QTableView(self.down_grid_group_box)
        self.down_grid_table_view.setGeometry(QtCore.QRect(10, 60, 231, 441))
        self.down_grid_table_view.setObjectName("down_grid_table_view")
        self.load_down_grid_push_button = QtWidgets.QPushButton(self.down_grid_group_box)
        self.load_down_grid_push_button.setGeometry(QtCore.QRect(10, 30, 91, 24))
        self.load_down_grid_push_button.setObjectName("load_down_grid_push_button")
        self.save_down_grid_push_button = QtWidgets.QPushButton(self.down_grid_group_box)
        self.save_down_grid_push_button.setGeometry(QtCore.QRect(110, 30, 91, 24))
        self.save_down_grid_push_button.setObjectName("save_down_grid_push_button")
        self.append_down_grid_item_push_button = QtWidgets.QPushButton(self.down_grid_group_box)
        self.append_down_grid_item_push_button.setGeometry(QtCore.QRect(210, 510, 31, 24))
        self.append_down_grid_item_push_button.setText("")
        self.append_down_grid_item_push_button.setObjectName("append_down_grid_item_push_button")
        self.grid_table_view = QtWidgets.QTableView(self.grid_group_box)
        self.grid_table_view.setGeometry(QtCore.QRect(10, 80, 231, 441))
        self.grid_table_view.setObjectName("grid_table_view")
        self.load_grid_push_button = QtWidgets.QPushButton(self.grid_group_box)
        self.load_grid_push_button.setGeometry(QtCore.QRect(10, 50, 91, 24))
        self.load_grid_push_button.setObjectName("load_grid_push_button")
        self.save_grid_push_button = QtWidgets.QPushButton(self.grid_group_box)
        self.save_grid_push_button.setGeometry(QtCore.QRect(110, 50, 91, 24))
        self.save_grid_push_button.setObjectName("save_grid_push_button")
        self.append_grid_item_push_button = QtWidgets.QPushButton(self.grid_group_box)
        self.append_grid_item_push_button.setGeometry(QtCore.QRect(210, 530, 31, 24))
        self.append_grid_item_push_button.setText("")
        self.append_grid_item_push_button.setObjectName("append_grid_item_push_button")
        self.margin_name_label = QtWidgets.QLabel(self.grid_group_box)
        self.margin_name_label.setGeometry(QtCore.QRect(10, 580, 61, 16))
        self.margin_name_label.setObjectName("margin_name_label")
        self.margin_double_spin_box = QtWidgets.QDoubleSpinBox(self.grid_group_box)
        self.margin_double_spin_box.setGeometry(QtCore.QRect(70, 580, 111, 22))
        self.margin_double_spin_box.setMaximum(1000000.0)
        self.margin_double_spin_box.setObjectName("margin_double_spin_box")
        self.margin_unit_label = QtWidgets.QLabel(self.grid_group_box)
        self.margin_unit_label.setGeometry(QtCore.QRect(190, 580, 49, 16))
        self.margin_unit_label.setObjectName("margin_unit_label")
        self.detector_name_label = QtWidgets.QLabel(self.grid_group_box)
        self.detector_name_label.setGeometry(QtCore.QRect(10, 610, 61, 16))
        self.detector_name_label.setObjectName("detector_name_label")
        self.detector_spin_box = QtWidgets.QSpinBox(self.grid_group_box)
        self.detector_spin_box.setGeometry(QtCore.QRect(70, 610, 111, 22))
        self.detector_spin_box.setMinimum(-1000000)
        self.detector_spin_box.setMaximum(1000000)
        self.detector_spin_box.setObjectName("detector_spin_box")
        self.interpolate_check_box = QtWidgets.QCheckBox(self.grid_group_box)
        self.interpolate_check_box.setGeometry(QtCore.QRect(10, 640, 101, 20))
        self.interpolate_check_box.setObjectName("interpolate_check_box")
        self.detector_hint_label = QtWidgets.QLabel(self.grid_group_box)
        self.detector_hint_label.setGeometry(QtCore.QRect(190, 610, 49, 16))
        self.detector_hint_label.setObjectName("detector_hint_label")

        self.retranslateUi(OnMrBuildDialog)
        self.buttonBox.accepted.connect(OnMrBuildDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(OnMrBuildDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(OnMrBuildDialog)

    def retranslateUi(self, OnMrBuildDialog):
        _translate = QtCore.QCoreApplication.translate
        OnMrBuildDialog.setWindowTitle(_translate("OnMrBuildDialog", "Настройки построения АХ"))
        self.sequence_label.setText(_translate("OnMrBuildDialog", "Порядок изменения физ. величины:"))
        self.grid_group_box.setTitle(_translate("OnMrBuildDialog", "Сетка"))
        self.down_grid_group_box.setTitle(_translate("OnMrBuildDialog", "Отдельная сетка для спуска"))
        self.load_down_grid_push_button.setText(_translate("OnMrBuildDialog", "Загрузить..."))
        self.save_down_grid_push_button.setText(_translate("OnMrBuildDialog", "Сохранить..."))
        self.load_grid_push_button.setText(_translate("OnMrBuildDialog", "Загрузить..."))
        self.save_grid_push_button.setText(_translate("OnMrBuildDialog", "Сохранить..."))
        self.margin_name_label.setText(_translate("OnMrBuildDialog", "Ворота:  ±"))
        self.margin_unit_label.setText(_translate("OnMrBuildDialog", "TextLabel"))
        self.detector_name_label.setText(_translate("OnMrBuildDialog", "Детектор:"))
        self.interpolate_check_box.setText(_translate("OnMrBuildDialog", "Интерполяция"))
        self.detector_hint_label.setText(_translate("OnMrBuildDialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OnMrBuildDialog = QtWidgets.QDialog()
    ui = Ui_OnMrBuildDialog()
    ui.setupUi(OnMrBuildDialog)
    OnMrBuildDialog.show()
    sys.exit(app.exec())
