# Form implementation generated from reading ui file 'on_open_file_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OnOpenFileDialog(object):
    def setupUi(self, OnOpenFileDialog):
        OnOpenFileDialog.setObjectName("OnOpenFileDialog")
        OnOpenFileDialog.resize(400, 380)
        self.buttonBox = QtWidgets.QDialogButtonBox(OnOpenFileDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 320, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.etalon_settings_group_box = QtWidgets.QGroupBox(OnOpenFileDialog)
        self.etalon_settings_group_box.setGeometry(QtCore.QRect(10, 90, 381, 131))
        self.etalon_settings_group_box.setFlat(False)
        self.etalon_settings_group_box.setObjectName("etalon_settings_group_box")
        self.k_label = QtWidgets.QLabel(self.etalon_settings_group_box)
        self.k_label.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.k_label.setObjectName("k_label")
        self.u0_label = QtWidgets.QLabel(self.etalon_settings_group_box)
        self.u0_label.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.u0_label.setObjectName("u0_label")
        self.unit_label = QtWidgets.QLabel(self.etalon_settings_group_box)
        self.unit_label.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.unit_label.setObjectName("unit_label")
        self.k_line_edit = QtWidgets.QLineEdit(self.etalon_settings_group_box)
        self.k_line_edit.setGeometry(QtCore.QRect(90, 30, 281, 22))
        self.k_line_edit.setObjectName("k_line_edit")
        self.u0_line_edit = QtWidgets.QLineEdit(self.etalon_settings_group_box)
        self.u0_line_edit.setGeometry(QtCore.QRect(90, 60, 281, 22))
        self.u0_line_edit.setObjectName("u0_line_edit")
        self.unit_line_edit = QtWidgets.QLineEdit(self.etalon_settings_group_box)
        self.unit_line_edit.setGeometry(QtCore.QRect(90, 90, 281, 22))
        self.unit_line_edit.setObjectName("unit_line_edit")
        self.ds_settings_group_box = QtWidgets.QGroupBox(OnOpenFileDialog)
        self.ds_settings_group_box.setGeometry(QtCore.QRect(9, 10, 381, 71))
        self.ds_settings_group_box.setObjectName("ds_settings_group_box")
        self.ds_label = QtWidgets.QLabel(self.ds_settings_group_box)
        self.ds_label.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.ds_label.setObjectName("ds_label")
        self.ds_line_edit = QtWidgets.QLineEdit(self.ds_settings_group_box)
        self.ds_line_edit.setGeometry(QtCore.QRect(90, 30, 281, 22))
        self.ds_line_edit.setObjectName("ds_line_edit")
        self.other_settings_group_box = QtWidgets.QGroupBox(OnOpenFileDialog)
        self.other_settings_group_box.setGeometry(QtCore.QRect(10, 230, 381, 71))
        self.other_settings_group_box.setObjectName("other_settings_group_box")
        self.show_raw_signals_check_box = QtWidgets.QCheckBox(self.other_settings_group_box)
        self.show_raw_signals_check_box.setGeometry(QtCore.QRect(10, 30, 201, 20))
        self.show_raw_signals_check_box.setObjectName("show_raw_signals_check_box")

        self.retranslateUi(OnOpenFileDialog)
        self.buttonBox.accepted.connect(OnOpenFileDialog.accept)
        self.buttonBox.rejected.connect(OnOpenFileDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OnOpenFileDialog)

    def retranslateUi(self, OnOpenFileDialog):
        _translate = QtCore.QCoreApplication.translate
        OnOpenFileDialog.setWindowTitle(_translate("OnOpenFileDialog", "Dialog"))
        self.etalon_settings_group_box.setTitle(_translate("OnOpenFileDialog", "Преобразование сигнала эталона"))
        self.k_label.setText(_translate("OnOpenFileDialog", "K, В/ед. изм.:"))
        self.u0_label.setText(_translate("OnOpenFileDialog", "U0, В:"))
        self.unit_label.setText(_translate("OnOpenFileDialog", "Ед. изм.:"))
        self.ds_settings_group_box.setTitle(_translate("OnOpenFileDialog", "Усреднение сигнала"))
        self.ds_label.setText(_translate("OnOpenFileDialog", "Интервал, с"))
        self.other_settings_group_box.setTitle(_translate("OnOpenFileDialog", "Прочее"))
        self.show_raw_signals_check_box.setText(_translate("OnOpenFileDialog", "Показывать исходные сигналы"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OnOpenFileDialog = QtWidgets.QDialog()
    ui = Ui_OnOpenFileDialog()
    ui.setupUi(OnOpenFileDialog)
    OnOpenFileDialog.show()
    sys.exit(app.exec())
